# FOR CREATING THE USER DEFINED MODULE WE WANT TO CREATE THE PYTHON FILE IN THE SAME FOLDER AND NAME IT AS THE NAME OF MODULE AND WRITE THE FUNCTIONS IN IT 
# THEN WE CAN IMPORT THAT IN OUR MAIN CODE!!!!

import userexample 
print(userexample.pi)

print(userexample.cube(3))

print(userexample.area(2))